services:
  postgres:
    image: postgres:17
    container_name: rpgtrade-postgres
    environment:
      POSTGRES_DB: rpgtrade
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - rpgtrade_postgres_data:/var/lib/postgresql/data

volumes:
  rpgtrade_postgres_data: