FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["RpgTrade.Web/RpgTrade.Web.csproj", "RpgTrade.Web/"]

RUN dotnet restore "RpgTrade.Web/RpgTrade.Web.csproj"

COPY . .

RUN dotnet publish "RpgTrade.Web/RpgTrade.Web.csproj" -c Release -o /app/publish

FROM runtime AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "RpgTrade.Web.dll"]