FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["RpgTrade.Domain/RpgTrade.Domain.csproj", "RpgTrade.Domain/"]
COPY ["RpgTrade.Application/RpgTrade.Application.csproj", "RpgTrade.Application/"]
COPY ["RpgTrade.Infrastructure/RpgTrade.Infrastructure.csproj", "RpgTrade.Infrastructure/"]
COPY ["RpgTrade.Api/RpgTrade.Api.csproj", "RpgTrade.Api/"]

RUN dotnet restore "RpgTrade.Api/RpgTrade.Api.csproj"

COPY . .

RUN dotnet publish "RpgTrade.Api/RpgTrade.Api.csproj" -c Release -o /app/publish

FROM runtime AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "RpgTrade.Api.dll"]