// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RpgTrade.Infrastructure.Persistence;

#nullable disable

namespace RpgTrade.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModifierDefinitionItemClasses", b =>
                {
                    b.Property<int>("ModifierDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemClassId")
                        .HasColumnType("integer");

                    b.HasKey("ModifierDefinitionId", "ItemClassId");

                    b.HasIndex("ItemClassId");

                    b.ToTable("ModifierDefinitionItemClasses", (string)null);
                });

            modelBuilder.Entity("RpgTrade.Domain.BaseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ItemClassId");

                    b.ToTable("BaseTypes", (string)null);
                });

            modelBuilder.Entity("RpgTrade.Domain.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BaseTypeId");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("RpgTrade.Domain.ItemClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ItemClasses", (string)null);
                });

            modelBuilder.Entity("RpgTrade.Domain.ItemModifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("ModifierDefinitionId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ModifierDefinitionId");

                    b.ToTable("ItemModifiers", (string)null);
                });

            modelBuilder.Entity("RpgTrade.Domain.ModifierDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ModifierDefinitions", (string)null);
                });

            modelBuilder.Entity("ModifierDefinitionItemClasses", b =>
                {
                    b.HasOne("RpgTrade.Domain.ItemClass", null)
                        .WithMany()
                        .HasForeignKey("ItemClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RpgTrade.Domain.ModifierDefinition", null)
                        .WithMany()
                        .HasForeignKey("ModifierDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgTrade.Domain.BaseType", b =>
                {
                    b.HasOne("RpgTrade.Domain.ItemClass", "ItemClass")
                        .WithMany()
                        .HasForeignKey("ItemClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemClass");
                });

            modelBuilder.Entity("RpgTrade.Domain.Item", b =>
                {
                    b.HasOne("RpgTrade.Domain.BaseType", "BaseType")
                        .WithMany()
                        .HasForeignKey("BaseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseType");
                });

            modelBuilder.Entity("RpgTrade.Domain.ItemModifier", b =>
                {
                    b.HasOne("RpgTrade.Domain.Item", null)
                        .WithMany("Modifiers")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgTrade.Domain.ModifierDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("ModifierDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("RpgTrade.Domain.Item", b =>
                {
                    b.Navigation("Modifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
